#! /bin/bash

ifort -openmp mt.f90 MotilityAssayActin2MotorsParameters_v3.f90 MotilityAssayConfinements_v1.f90 MotilityAssaySubstrateDeformation_v2.f90 MotilityAssayForceForceFunctions_v2.f90 MotilityAssayActin2MotorsMain_v6.f90
